version: '3'
services:
  ghost:
    container_name: ghost
    build:
      context: .
      dockerfile: ./docker/DockerfileDockerize
    volumes:
      - ./docker/config.production.json:/srv/ghost/config.production.json:ro
      - ./ghost/core/content/data:/srv/ghost/content/data
      - ./ghost/core/content/logs:/srv/ghost/content/logs
      - ./ghost/core/content/settings:/srv/ghost/content/settings
    ports:
      - '8180:2368'
    tty: true
    restart: always
    depends_on:
      - mysql
    command: >
      bash -c "dockerize -wait tcp://mysql:3306 &&
      node /srv/ghost/index.js"
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./conf.d:/etc/mysql/conf.d:ro
    restart: always
    environment:
      MYSQL_ROOT_HOST: mysql
      MYSQL_ROOT_PASSWORD: ghost
      MYSQL_USER: ghost
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: ghost
    expose:
      - 3306

volumes:
  mysql-volume: